api_platform:
    title: 'API de Concert'
    description: "Projet d'école en groupe, de création d'une API Symfony lié a un front en React"
    enable_nelmio_api_doc: false
    # Enable the Swagger documentation and export.
    enable_swagger: true
    # Enable Swagger ui.
    enable_swagger_ui: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header